config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  resources :wikis

  devise_for :users

  get 'about' => 'welcome#about'

  resources :charges, only: [:new, :create]
  resources :refunds, only: [:new, :create]
  resources :collaborations, only: [:create, :destroy]
end

app/models/charge.rb
class Charge < ActiveRecord::Base
  belongs_to :user
end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :wikis, dependent: :destroy
  has_many :charges, dependent: :destroy
  has_many :collaborations
  has_many :wiki_collaborations, through: :collaborations, source: :wiki
  after_initialize :init

  def init
    self.role ||= 'standard'
  end

  def upgrade
    update_attribute(:role, 'premium')
  end

  def downgrade
    update_attribute(:role, 'standard')
  end

  def admin?
    role == 'admin'
  end

  def premium?
    role == 'premium'
  end

  def standard?
    role == 'standard'
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborations
  has_many :users, through: :collaborations

  scope :publicly_viewable, -> { where(private: false) }

  extend FriendlyId
  friendly_id :title, use: :slugged


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def after_sign_in_path_for(resource)
    wikis_path
  end
 
   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
     devise_parameter_sanitizer.for(:account_update) << :name
   end 

   private

    def user_not_authorized
      flash[:error] = 'You are not authorized'
      redirect_to(request.referrer || root_path)
    end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "upgrade to premium - #{current_user.name}"
    }
  end

  def create
    @amount ||= 1500

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card => params[:stripeToken]
      )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => "premium membership for #{current_user.email}",
      :currency => 'usd'
    )
  
  current_user.charges.create(charge_id: charge.id)
  current_user.update(role: "premium")
  flash[:notice] = "Thank you for supporting blocipedia, #{current_user.email}!"
  redirect_to root_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end



end

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController

  def new
    @collaboration = Collaboration.new
  end

  def create
    @wiki = Wiki.find(params[:wiki_id])
    @other_user = User.find_by email: params[:collaboration][:user_id]
    if @other_user == nil
      flash[:notice] = "There is no registered user with that email address"
      redirect_to edit_wiki_path(@wiki) and return
    end
    if collaboration = Collaboration.find_by(user_id: @other_user.id, wiki_id: @wiki.id)
      flash[:notice] = "#{@other_user.name} is already collaborating on this wiki"
      redirect_to edit_wiki_path(@wiki) and return
    end
    @collaboration = Collaboration.new(collaboration_params)
    authorize @collaboration
    @collaboration.user_id = @other_user.id
    @collaboration.wiki_id = @wiki.id
    if @collaboration.save
      flash[:notice] = "#{@other_user.name} has been added as a collaborator for this wiki."
      redirect_to edit_wiki_path(@wiki)
    else
      flash[:error] = "There was an error adding a collaborator.  Please try again."
      render :new
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    @collaboration = @wiki.collaborations.first
    if @collaboration.destroy
      flash[:notice] = "That collaborator has been removed from this wiki."
      redirect_to edit_wiki_path(@wiki)
    else
      flash[:error] = "There was an error deleting the collaborator.  Please try again."
      render :new
    end
  end

  private

    def collaboration_params
      params.require(:collaboration).permit(:wiki_id, :user_id)
    end

end

app/controllers/refunds_controller.rb
class RefundsController < ApplicationController
  def new    
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "downgrade to standard - #{current_user.name}"
    }
  end

  def create
    charge = current_user.charges.last
    stripe_charge = Stripe::Charge.retrieve(charge.charge_id)
    refund_amount = (1500 * (1- (Date.today - charge.created_at.to_date) / 365)).to_f.round
    if refund = stripe_charge.refunds.create(amount:refund_amount)
      current_user.update(role: "standard")
      @user_wikis = current_user.wikis
      @user_wikis.each { |wiki| wiki.update_attribute(:private, false) }
      flash[:notice] = "You have been refunded #{view_context.number_to_currency(refund_amount/100, precision: 0)}.  Hope to have you back soon, #{current_user.email}!"
    end
      redirect_to root_path

  end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    @user = current_user
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    @wiki.private ||= false
    authorize @wiki
    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash[:error] = "There was an error saving the wiki.  Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki
    #@collaborators = User.where(id: [@wiki.collaborations.map{|c| c.user_id}.join] )
    @collaborations = @wiki.collaborations

  end

  def update
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki
    if @wiki.update_attributes(wiki_params)
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash[:error] = "There was an error and the wiki was not updated.  Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted."
      redirect_to wikis_path
    else
      flash[:error] = "There was an error and the wiki was not deleted.  Please try again."
      render :show
    end
  end

  private

    def wiki_params
      params.require(:wiki).permit(:title, :body, :private)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    !current_user.nil?
  end

  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/refunds_helper.rb
module RefundsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.haml
%h2
  You have been charged
  %strong
    $15.00
  , and your account has been upgraded to premium. 
%h2
  Thank you for your support!

= link_to "Make a new wiki", new_wiki_path

app/views/charges/new.html.erb
<h1>Upgrade to premium</h1>

<div class="row">
  <div class="col-md-4">
    <p>Become a premium member of blocipedia!</p>
      <ul>
        <li>placeholder benefit 1.</li>
        <li>placeholder benefit 2.</li>
        <li>placeholder benefit 3.</li>
      </ul>

  <%= link_to "Never mind...", new_wiki_path %>
  </div>

<div class="col-md-8">

  <%= form_tag charges_path do %>
    <article>
      <label class="amount">
        <span>Amount: $15.00</span></br>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js"
            class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="<%= @stripe_btn_data[:description] %>"
            data-amount=<%= @stripe_btn_data[:amount] %> >
    </script>
  <% end %></br>



</div>

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    Blocipedia
  %nav
    %ul
      %li= link_to "About",   about_path
      %li= link_to "BLOC", "http://bloc.io/"
          

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
  .container
    = link_to "Blocipedia", root_path, id: "logo"
    %nav
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Home", root_path
        - if logged_in?
          %li= link_to "Wikis", wikis_path
          %li.dropdown
            %li= link_to (current_user.name || current_user.email), edit_user_registration_path(current_user)
            %li.divider
              %li= link_to "Sign out", destroy_user_session_path, method: :delete
        -else
          %li= link_to "Sign In", new_user_session_path
          %li= link_to "Sign Up", new_user_registration_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.2/marked.min.js' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
     <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div> 
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %> 
<%= yield %>
  <%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
     <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div> 
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %> 
<%= yield %>
  <%= render 'layouts/footer' %>

</body>
</html>

app/views/refunds/new.html.haml
%h1 Downgrade to standard
.row
  .col-md-4
    %p
      Cancel your premium blocipedia membership
      %ul
        %li placeholder comment 1.
        %li placeholder comment 2.
        %li placeholder comment 3.

  = link_to "Never mind...", new_wiki_path

  .col-md-8
    %p Are you sure?
    %p By cancelling your premium subscription you will lose the ability to create private wikis.
    %p All of your private wikis will become public.  The will be completely open for viewing and updating.

    = link_to "No, I don't want to do that.", root_path
    %br
    = link_to "Yes, I am sure.  Cancel my premium account", refunds_path, method: :post

app/views/welcome/about.html.haml
%br
.jumbotron
  %h1 About Blocipedia
  %p Created by Bradley Gohman
  %br
    = link_to "Visit me on Github", "https://github.com/bgohman", class: "social-btn"

app/views/welcome/index.html.haml
%br
.jumbotron
  %h1 Blocipedia
  %p Make your own public and private wiki articles.
  %p
    - if logged_in?
      = link_to "View wikis", wikis_path
      or
      = link_to "Make a new Wiki", new_wiki_path
    - else
      = link_to "Sign In", new_user_session_path, class: 'btn btn-primary'
      or
      = link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary'
      today!

app/views/wikis/edit.html.haml
%h1 Edit Wiki
.row
  .col-md-6
    %h2 edit
    = form_for @wiki do |f|
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control', placeholder: "wiki title"
      .form-group
        = f.label :body
        = f.text_area :body, rows: 8, class: 'form-control', placeholder: "wiki body..."
      .form-group
        - if policy(Wiki.new).premium?
          - if current_user == @wiki.user
            .form-group
              = f.label :private
              = f.check_box :private, class: 'form-control'
        -else
          = link_to "Upgrade to a premium account?", new_charge_path
          %br
        = f.submit "Save", class: 'btn btn-success'
  .col-md-6
    #title-preview
    #body-preview


- if policy(Wiki.new).premium? && current_user == @wiki.user && @wiki.private?
  .row
    .col-md-4
      %h4 
        Wiki Collaborators
      - @collaborations.each do |collaboration|
        %p
          = collaboration.user.name 
          | 
          = link_to "remove this collaborator", collaboration_path, method: :delete, data: { confirm: "Are you sure?" }   
      = form_for(@wiki.collaborations.build) do |f|
        .form-group
          = hidden_field_tag :wiki_id, @wiki.id
          = f.label "Add collaborators:"
          = f.text_field :user_id, class: 'form-control', placeholder: "enter the user's email"
          = f.submit "Add"

app/views/wikis/index.html.haml
%h1 Wikis
- if policy(Wiki.new).create?
  = link_to "Make a new Wiki", new_wiki_path, class: 'btn'
.center
  - @wikis.each do |wiki|
    .media
      .media-body
        %h4.media-heading= link_to wiki.title, wiki

app/views/wikis/new.html.haml
%h1 New Wiki

.row
  .col-md-4
    %p
      Make a new wiki
      %ul
        %li placeholder instruction 1.
        %li placeholder instruction 2.
        %li placeholder instruction 3.

  - unless policy(Wiki.new).premium?
    = link_to "Upgrade to a premium account", new_charge_path

  .col-md-8
    = form_for @wiki do |f|
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control', placeholder: "wiki title"
      .form-group
        = f.label :body
        = f.text_area :body, rows: 8, class: 'form-control', placeholder: "wiki body..."
      - if policy(Wiki.new).premium?
        .form-group
          = f.label :private
          = f.check_box :private, class: 'form-control'
      - else
        = link_to "Upgrade to a premium account?", new_charge_path
        %br

      = f.submit "Save", class: 'btn btn-success'

app/views/wikis/show.html.haml
%h1= markdown_to_html @wiki.title

%p= markdown_to_html @wiki.body

- if policy(@wiki).edit?
  = link_to "Edit", edit_wiki_path(@wiki), class: 'btn'
- if policy(@wiki).destroy?
  = link_to "Delete", @wiki, method: :delete, class: 'btn', data: { confirm: 'Are you sure?' }